# Matrix Multiplication 

Of two order n matrices

In [1]:
class Mat():
    '''
    n= order of matrix
    iterable of size n*n with concatnated rows'''
    def __init__(self,n,lst):
        assert n**2==len(lst),'size error'
        mat=[]
        for i in range(n):
            mat.append(list(lst[i*n:i*n+n]))
        self.mat=mat
        self.order=n
        inv=[]
        for i in range(n):
            l=[]
            for j in range(n):
                l.append(lst[i+j*n])
            inv.append(list(l))
        self.T=inv
    def __call__(self):
        return self.mat

## Normal Brute Force

In [2]:
def brute_multiply(mat1,mat2):
    n=mat1.order
    nmat=[]
    for i in range(n):
        for j in range(n):
            nmat.append(sum(map(lambda x,y : x*y,mat1()[i],mat2.T[j])))
    return Mat(n,nmat)

In [3]:
import random
mat1=Mat(8,random.sample(range(1000000),64))
mat2=Mat(8,random.sample(range(1000000),64))

In [4]:
import numpy as np
a=np.array(mat1(),dtype='int64')
b=np.array(mat2(),dtype='int64')

In [5]:
%timeit range(10)
brute_multiply(mat1,mat2)()

173 ns ± 21.7 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)


[[1829543672303,
  1424035001316,
  1908885254937,
  1864720418435,
  1540642807553,
  1544435717407,
  2388420125116,
  2116237958150],
 [2115348740429,
  2067624797866,
  1886319515910,
  1844589393204,
  1680696440115,
  1971653927967,
  2162087700242,
  2692836332450],
 [1441989418025,
  1740465583481,
  1642319672497,
  1638828971011,
  948710135229,
  694437863477,
  1736542686437,
  1837372988191],
 [1667198490960,
  1473085572339,
  1160562112544,
  1714151771641,
  1329019129634,
  1689235976181,
  1598964724841,
  1835001548227],
 [1545313016773,
  1521491140222,
  1809997150247,
  1763460342186,
  1239818566431,
  1371768456961,
  2057074191510,
  2086334769670],
 [1874035001831,
  1893346271951,
  2288156443055,
  2315164378800,
  1494503307304,
  1580851623938,
  2748411852394,
  2379304057784],
 [2073537649640,
  2327727625651,
  2803451044084,
  2868735816409,
  1787820905723,
  1750568424305,
  3109597005706,
  2685596685177],
 [853039593565,
  741376879341,
  140798956

In [6]:
%timeit range(10)
np.matmul(a,b)

161 ns ± 6.91 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)


array([[1829543672303, 1424035001316, 1908885254937, 1864720418435,
        1540642807553, 1544435717407, 2388420125116, 2116237958150],
       [2115348740429, 2067624797866, 1886319515910, 1844589393204,
        1680696440115, 1971653927967, 2162087700242, 2692836332450],
       [1441989418025, 1740465583481, 1642319672497, 1638828971011,
         948710135229,  694437863477, 1736542686437, 1837372988191],
       [1667198490960, 1473085572339, 1160562112544, 1714151771641,
        1329019129634, 1689235976181, 1598964724841, 1835001548227],
       [1545313016773, 1521491140222, 1809997150247, 1763460342186,
        1239818566431, 1371768456961, 2057074191510, 2086334769670],
       [1874035001831, 1893346271951, 2288156443055, 2315164378800,
        1494503307304, 1580851623938, 2748411852394, 2379304057784],
       [2073537649640, 2327727625651, 2803451044084, 2868735816409,
        1787820905723, 1750568424305, 3109597005706, 2685596685177],
       [ 853039593565,  741376879341, 140

##   Recursive Algorithm

In [7]:
def rec_multiply(x,y):
    import numpy as np
    if str(type(x)) != '''<class 'numpy.ndarray'>''' :
        x=np.array(x,dtype='int64')
    if str(type(y)) != '''<class 'numpy.ndarray'>''' : 
        y=np.array(y,dtype='int64')
    
    n=x.shape[0]
    if x.shape == (1,) or x.shape == (1,1):
        return x*y
    else :
        A=x[:n//2,:n//2]
        B=x[:n//2,n//2:]
        C=x[n//2:,:n//2]
        D=x[n//2:,n//2:]
        E=y[:n//2,:n//2]
        F=y[:n//2,n//2:]
        G=y[n//2:,:n//2]
        H=y[n//2:,n//2:]
        AE=rec_multiply(A,E)
        BG=rec_multiply(B,G)
        AF=rec_multiply(A,F)
        BH=rec_multiply(B,H)
        CE=rec_multiply(C,E)
        DG=rec_multiply(D,G)
        CF=rec_multiply(C,F)
        DH=rec_multiply(D,H)
        xy=np.copy(x)
        xy[:n//2,:n//2]=AE+BG
        xy[:n//2,n//2:]=AF+BH
        xy[n//2:,:n//2]=CE+DG
        xy[n//2:,n//2:]=CF+DH
        return xy
        
        

In [8]:
%timeit range(10)
rec_multiply(a,b)

163 ns ± 3.6 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)


array([[1829543672303, 1424035001316, 1908885254937, 1864720418435,
        1540642807553, 1544435717407, 2388420125116, 2116237958150],
       [2115348740429, 2067624797866, 1886319515910, 1844589393204,
        1680696440115, 1971653927967, 2162087700242, 2692836332450],
       [1441989418025, 1740465583481, 1642319672497, 1638828971011,
         948710135229,  694437863477, 1736542686437, 1837372988191],
       [1667198490960, 1473085572339, 1160562112544, 1714151771641,
        1329019129634, 1689235976181, 1598964724841, 1835001548227],
       [1545313016773, 1521491140222, 1809997150247, 1763460342186,
        1239818566431, 1371768456961, 2057074191510, 2086334769670],
       [1874035001831, 1893346271951, 2288156443055, 2315164378800,
        1494503307304, 1580851623938, 2748411852394, 2379304057784],
       [2073537649640, 2327727625651, 2803451044084, 2868735816409,
        1787820905723, 1750568424305, 3109597005706, 2685596685177],
       [ 853039593565,  741376879341, 140

## Strassen's Algo 

In [9]:
def strassen_multiply(x,y):
    import numpy as np
    if str(type(x)) != '''<class 'numpy.ndarray'>''' :
        x=np.array(x,dtype='int64')
    if str(type(y)) != '''<class 'numpy.ndarray'>''' : 
        y=np.array(y,dtype='int64')
    
    n=x.shape[0]
    if x.shape == (1,) or x.shape == (1,1):
        return x*y
    else :
        A=x[:n//2,:n//2]
        B=x[:n//2,n//2:]
        C=x[n//2:,:n//2]
        D=x[n//2:,n//2:]
        E=y[:n//2,:n//2]
        F=y[:n//2,n//2:]
        G=y[n//2:,:n//2]
        H=y[n//2:,n//2:]
        p1=strassen_multiply(A,F-H)
        p2=strassen_multiply(A+B,H)
        p3=strassen_multiply(C+D,E)
        p4=strassen_multiply(D,G-E)
        p5=strassen_multiply(A+D,E+H)
        p6=strassen_multiply(B-D,G+H)
        p7=strassen_multiply(A-C,E+F)
        xy=np.copy(x)
        xy[:n//2,:n//2]=p5+p4-p2+p6
        xy[:n//2,n//2:]=p1+p2
        xy[n//2:,:n//2]=p3+p4
        xy[n//2:,n//2:]=p1+p5-p3-p7
        return xy
        

In [11]:
%timeit range(10)
strassen_multiply(a,b)

163 ns ± 7.63 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)


array([[1829543672303, 1424035001316, 1908885254937, 1864720418435,
        1540642807553, 1544435717407, 2388420125116, 2116237958150],
       [2115348740429, 2067624797866, 1886319515910, 1844589393204,
        1680696440115, 1971653927967, 2162087700242, 2692836332450],
       [1441989418025, 1740465583481, 1642319672497, 1638828971011,
         948710135229,  694437863477, 1736542686437, 1837372988191],
       [1667198490960, 1473085572339, 1160562112544, 1714151771641,
        1329019129634, 1689235976181, 1598964724841, 1835001548227],
       [1545313016773, 1521491140222, 1809997150247, 1763460342186,
        1239818566431, 1371768456961, 2057074191510, 2086334769670],
       [1874035001831, 1893346271951, 2288156443055, 2315164378800,
        1494503307304, 1580851623938, 2748411852394, 2379304057784],
       [2073537649640, 2327727625651, 2803451044084, 2868735816409,
        1787820905723, 1750568424305, 3109597005706, 2685596685177],
       [ 853039593565,  741376879341, 140